src/main/java/by/sign/controller/form/ProxyForm.java
package by.sign.controller.form;

import java.io.Serializable;
import java.util.Date;

import by.sign.enums.ProxyType;
import by.sign.model.ServiceUser;

public class ProxyForm implements Serializable {
	private static final long serialVersionUID = -4201553523388131159L;

	private ProxyType proxyType = ProxyType.UNPROTECTED;
	private Date validFrom;
	private int validDays = 100;
	private ServiceUser targetUser;

	public ProxyType[] getProxyTypes() {
		return ProxyType.values();
	}

	public ProxyType getProxyType() {
		return proxyType;
	}

	public void setProxyType(ProxyType proxyType) {
		this.proxyType = proxyType;
	}

	public Date getValidFrom() {
		return validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public int getValidDays() {
		return validDays;
	}

	public void setValidDays(int validDays) {
		this.validDays = validDays;
	}

	public ServiceUser getTargetUser() {
		return targetUser;
	}

	public void setTargetUser(ServiceUser targetUser) {
		this.targetUser = targetUser;
	}

	@Override
	public String toString() {
		return "ProxyForm [proxyType=" + proxyType + ", validFrom=" + validFrom + ", validDays=" + validDays
				+ ", targetUser=" + targetUser + "]";
	}

}

src/main/java/by/sign/model/ServiceUser.java
package by.sign.model;

import java.math.BigInteger;
import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;

import by.sign.model.mapper.MapperModel;
import by.sign.model.mapper.Prop;

/**
 * User of sign service. Belongs to specific company, except service administrator.
 * Model contains DSA public and private keys
 * 
 * @author Raman Yelianevich
 * @version 1.0
 */
@MapperModel
public class ServiceUser extends User {
	private static final long serialVersionUID = 809204807080927669L;

	@Prop
	private String email;

	@Prop
	private String firstName;

	@Prop
	private String lastName;

	@Prop
	private String position;

	@Prop
	private BigInteger x;

	@Prop
	private BigInteger y;

	public ServiceUser(String username, String password, Collection<? extends GrantedAuthority> authorities) {
		super(username, password, authorities);
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public BigInteger getY() {
		return y;
	}

	public void setY(BigInteger y) {
		this.y = y;
	}

	public BigInteger getX() {
		return x;
	}

	public void setX(BigInteger x) {
		this.x = x;
	}

	public String getFullName() {
		return firstName + " " + lastName;
	}

	@Override
	public String toString() {
		return "ServiceUser [firstName=" + firstName + ", lastName=" + lastName + ", getUsername()=" + getUsername()
				+ "]";
	}

}

src/main/java/by/sign/model/mapper/IModelMapper.java
package by.sign.model.mapper;

import com.mongodb.DBObject;

/**
 * Can map {@link DBObject} to {@code T} model type and vice versa
 * @author Raman Yelianevich
 * @param <T> - model type
 */
public interface IModelMapper <T> {
	
	/**
	 * Map model to {@link DBObject}. Each field should be mapped with
	 * {@link prop} annotation.
	 */
	DBObject toDbObject(T model);
	
	/**
	 * Restore model annotated with {@link MapperModel}. Each field that should
	 * be populated marked with {@link Prop} annotation.
	 * 
	 * @param model
	 *            - empty model object
	 * @param dbObj
	 *            - instance with properties to be resored
	 * @return populated {@code model}
	 */
	T restoreModel(DBObject dbObj, T model);
}

src/main/java/by/sign/controller/CompanyController.java
package by.sign.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.apache.commons.lang3.StringUtils;

import by.sign.model.Company;
import by.sign.model.ServiceUser;
import by.sign.service.CompanyService;
import by.sign.service.UserService;

public class CompanyController {

	private Company company;
	private UserService userService;
	private CompanyService companyService;

	public CompanyController() {
	}

	public void addCompany() {
		boolean addMode = StringUtils.isBlank(company.getCompanyId());
		boolean isAdded = companyService.addCompany(company);
		String msg = isAdded ? "Saved!" : "Not able to add company.";
		FacesContext f = FacesContext.getCurrentInstance();
		f.addMessage("messages", new FacesMessage(msg));
		if (isAdded && addMode) {
			company = new Company();
		}
	}

	public String toAddCompany() {
		company = new Company();
		return "/pages/admin/editCompany";
	}

	public String toEditCompany(String id) {
		company = companyService.getCompany(id);
		return "/pages/admin/editCompany";
	}

	public void deleteCompany(String id) {
		boolean isDeleted = companyService.deleteCompany(id);

		FacesContext f = FacesContext.getCurrentInstance();
		if (isDeleted) {
			String msg = "Successfully Deleted";
			f.addMessage("messages", new FacesMessage(msg));
		} else {
			String msg = "Cannot Delete";
			f.addMessage("messages", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Internal Error", msg));
		}
	}

	public List<Company> getCompanies() {
		return companyService.getCompaniesList();
	}

	public List<ServiceUser> completeUser(String nameQuery) {
		List<ServiceUser> suggestions = userService.findUser(nameQuery);
		return suggestions;
	}

	public Company getCompany() {
		return company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public void setCompanyService(CompanyService companyService) {
		this.companyService = companyService;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}
}

src/main/java/by/sign/controller/ProxyController.java
package by.sign.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.joda.time.DateTime;
import org.joda.time.Period;

import by.sign.controller.form.ProxyForm;
import by.sign.model.ServiceUser;
import by.sign.service.ProxyService;
import by.sign.service.UserService;

public class ProxyController implements Serializable {
	private static final long serialVersionUID = -1066354690205221298L;

	private ProxyService proxyService;
	private UserService userService;
	private ProxyForm proxyForm;

	public ProxyController() {
	}

	public List<ServiceUser> completeUser(String nameQuery) {
		List<ServiceUser> suggestions = userService.findUser(nameQuery);
		return suggestions;
	}

	public String toGenerateProxy() {
		proxyForm = new ProxyForm();
		return "/pages/user/editProxy?faces-redirect=true";
	}

	public void sendProxy() {
		DateTime from = new DateTime(proxyForm.getValidFrom());
		Period period = new Period().withDays(proxyForm.getValidDays());
		boolean proxySent = proxyService.sendProxy(proxyForm.getTargetUser(), from, period, proxyForm.getProxyType());
		String msg = proxySent ? "Sent!" : "Was not able to send proxy.";
		FacesContext f = FacesContext.getCurrentInstance();
		f.addMessage("messages", new FacesMessage(msg));
		if (proxySent) {
			proxyForm = new ProxyForm();
		}
	}

	public void setProxyService(ProxyService proxyService) {
		this.proxyService = proxyService;
	}

	public UserService getUserService() {
		return userService;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	public ProxyForm getProxyForm() {
		return proxyForm;
	}

	public void setProxyForm(ProxyForm proxyForm) {
		this.proxyForm = proxyForm;
	}

}

src/main/java/by/sign/controller/SignController.java
package by.sign.controller;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import by.sign.controller.form.ValidationResult;
import by.sign.enums.ProxyType;
import by.sign.model.ServiceUser;
import by.sign.proxy.artifact.Proxy;
import by.sign.proxy.exception.WarrantNotValidException;
import by.sign.service.ProxyService;
import by.sign.service.UserService;

public class SignController implements Serializable {
	private static final long serialVersionUID = 9101093130933367019L;

	private ProxyService proxyService;
	private UserService userService;
	private FileUploadHandler fileUpload;
	private ProxyConverter proxyConverter;
	private Proxy proxy;
	private ProxyType proxyType;
	private StreamedContent file;
	private ValidationResult result;

	public SignController() {
	}

	public void signDocUsingProxy() {
		byte[] signature = null;
		try {
			signature = proxyService.sign(proxy, proxyType, fileUpload.getFile());
			InputStream stream = new ByteArrayInputStream(signature);
			file = new DefaultStreamedContent(stream, "application/octet-stream", fileUpload.getFileName() + ".sign");
			FacesMessage msg = new FacesMessage(fileUpload.getFileName() + " signed");
			FacesContext.getCurrentInstance().addMessage(null, msg);
		} catch (WarrantNotValidException e) {
			FacesMessage msg = new FacesMessage("Warrant is not valid for specified proxy");
			FacesContext.getCurrentInstance().addMessage(null, msg);
		}
	}

	public void signDsa() {
		FacesMessage msg = new FacesMessage(proxyType + " " + proxy.getTargetUser());
		FacesContext.getCurrentInstance().addMessage(null, msg);
	}

	public void verifySignature() {
		result = proxyService.verify(fileUpload.getFile(), fileUpload.getSignature());

		FacesMessage msg = new FacesMessage(result.isValid() ? "Valid" : "Not Valid");
		FacesContext.getCurrentInstance().addMessage("introPanel:growl", msg);
	}

	public List<? extends Proxy> getProxyList() {
		List<? extends Proxy> proxyList = null;
		if (proxyType == ProxyType.PROTECTED) {
			proxyList = proxyService.getProtectedProxies();
		} else if (proxyType == ProxyType.UNPROTECTED) {
			proxyList = proxyService.getUnprotectedProxies();
		}
		return proxyList;
	}

	public String getOriginalUserLabel(Proxy proxy) {
		ServiceUser user = userService.getUser(proxy.getOriginalY());
		String label = user.getFullName() + " (" + user.getUsername() + ") - " + proxy.getWarrant().getLabel();
		return label;
	}

	public String toProtectedProxy() {
		proxyType = ProxyType.PROTECTED;
		return "/pages/user/sign?faces-redirect=true";
	}

	public String toUnprotectedProxy() {
		proxyType = ProxyType.UNPROTECTED;
		return "/pages/user/sign?faces-redirect=true";
	}

	public String toDsa() {
		proxyType = null;
		return "/pages/user/sign?faces-redirect=true";
	}

	public void setFileUpload(FileUploadHandler fileUpload) {
		this.fileUpload = fileUpload;
	}

	public FileUploadHandler getFileUpload() {
		return fileUpload;
	}

	public StreamedContent getFile() {
		return file;
	}

	public ProxyType getProxyType() {
		return proxyType;
	}

	public void setProxyType(ProxyType proxyType) {
		this.proxyType = proxyType;
	}

	public ProxyService getProxyService() {
		return proxyService;
	}

	public void setProxyService(ProxyService proxyService) {
		this.proxyService = proxyService;
	}

	public Proxy getProxy() {
		return proxy;
	}

	public void setProxy(Proxy proxy) {
		this.proxy = proxy;
	}

	public UserService getUserService() {
		return userService;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	public ProxyConverter getProxyConverter() {
		return proxyConverter;
	}

	public void setProxyConverter(ProxyConverter proxyConverter) {
		this.proxyConverter = proxyConverter;
	}

	public ValidationResult getResult() {
		return result;
	}
}

src/main/java/by/sign/controller/UserController.java
package by.sign.controller;

import java.io.Serializable;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedProperty;
import javax.faces.context.FacesContext;

import org.apache.commons.lang3.StringUtils;
import org.apache.log4j.Logger;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;

import by.sign.controller.form.UserForm;
import by.sign.enums.Role;
import by.sign.model.ServiceUser;
import by.sign.service.UserService;
import by.sign.util.Utils;

/**
 * @author Raman Yelianevich
 * @version 1.0
 */
public class UserController implements Serializable {
	private static final long serialVersionUID = -8118462113323863022L;
	private static final Logger LOG = Logger.getLogger(UserController.class);
	private UserForm userForm;
	private String password;
	private String username;

	@ManagedProperty(value = "#{userService}")
	private UserService userService;

	@ManagedProperty(value = "#{authenticationManager}")
	private AuthenticationManager authenticationManager;

	public UserController() {
	}

	public String login() {
		try {
			Authentication request = new UsernamePasswordAuthenticationToken(this.getUsername(), this.getPassword());
			Authentication result = authenticationManager.authenticate(request);
			SecurityContextHolder.getContext().setAuthentication(result);
			this.setUsername(null);
			if (result.isAuthenticated() && Utils.hasRole(result.getAuthorities(), Role.ROLE_ADMIN)) {
				return "/pages/admin/admin?faces-redirect=true";
			}
		} catch (AuthenticationException e) {
			LOG.info("Authentivation failed. " + e.getMessage());
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Wrong credentials",
							"Username or password is incorrect"));
			return "/pages/pub/login";
		}
		return "/pages/user/home?faces-redirect=true";
	}

	public boolean checkRole(String role) {
		Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		if (principal.getClass().equals(String.class)) {
			// if "anonimousUser" logged in
			String anonimousUser = (String) principal;
			return StringUtils.equals(anonimousUser, role);
		}
		UserDetails user = (UserDetails) SecurityContextHolder.getContext().getAuthentication().getPrincipal();
		for (GrantedAuthority userRole : user.getAuthorities()) {
			if (userRole.getAuthority().equals(role)) {
				return true;
			}
		}
		return false;
	}
	
	public String toEditUser(String username) {
		ServiceUser su = userService.getUser(username);
		userForm = new UserForm(true);
		userForm.setServiceUser(su);
		userForm.setEmail(su.getEmail());
		userForm.setFirstName(su.getFirstName());
		userForm.setLastName(su.getLastName());
		userForm.setPassword(su.getPassword());
		userForm.setPosition(su.getPosition());
		userForm.setUsername(username);
		return "/pages/admin/editUser";
	}

	public String toAddUser() {
		userForm = new UserForm(false);
		return "/pages/admin/editUser";
	}

	public void saveUser() {
		boolean isSaved = userService.saveUser(userForm);
		FacesContext f = FacesContext.getCurrentInstance();
		if (isSaved) {
			String msg = "Successfully Saved";
			f.addMessage("messages", new FacesMessage(msg));
			userForm = new UserForm();
		} else {
			String msg = "Cannot Save. Username is not unique";
			f.addMessage("messages", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", msg));
		}
	}
	
	public void deleteUser(String username) {
		boolean isDeleted = userService.deleteUser(username);
		FacesContext f = FacesContext.getCurrentInstance();
		if (isDeleted) {
			String msg = "Successfully Deleted";
			f.addMessage("messages", new FacesMessage(msg));
		} else {
			String msg = "Cannot Delete";
			f.addMessage("messages", new FacesMessage(FacesMessage.SEVERITY_ERROR, "Error", msg));
		}
	}

	public List<ServiceUser> getUsers() {
		return userService.getUsers();
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public UserForm getUserForm() {
		return userForm;
	}

	public void setUserForm(UserForm userForm) {
		this.userForm = userForm;
	}

	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	public void setAuthenticationManager(AuthenticationManager authenticationManager) {
		this.authenticationManager = authenticationManager;
	}
}

src/main/webapp/pages/user/editProxy.xhtml
<ui:composition template="/template/layout/userLayout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<ui:define name="content">
		<p:growl id="messages" autoUpdate="true" showDetail="false" />
		<p:panel>
			<h:form id="proxyForm">
				<p:panel id="formPanel" header="Generate proxy">
					<h:panelGrid columns="3">
						<h:outputLabel for="validFrom" value="Valid from: " />
						<p:calendar id="validFrom"
							value="#{proxyBean.proxyForm.validFrom}" />
						<p:message for="validFrom" />

						<h:outputLabel for="daysValid" value="Days valid *" />
						<p:inputText id="daysValid"
							value="#{proxyBean.proxyForm.validDays}" required="true">
							<f:validateLongRange minimum="1" maximum="1000" />
						</p:inputText>
						<p:message for="daysValid" />

						<h:outputText value="Proxy Type: " />
						<p:selectOneMenu id="proxyType"
							value="#{proxyBean.proxyForm.proxyType}">
							<f:selectItems value="#{proxyBean.proxyForm.proxyTypes}"
								var="type" itemLabel="#{type.label}" itemValue="#{type}" />
						</p:selectOneMenu>
						<p:message for="proxyType" />

						<h:outputLabel for="user" value="Trusted User*" />
						<p:autoComplete id="user"
							value="#{proxyBean.proxyForm.targetUser}"
							completeMethod="#{proxyBean.completeUser}" var="user"
							itemLabel="#{user.fullName} (#{user.username})"
							itemValue="#{user}" converter="#{userConverter}" multiple="false"
							forceSelection="true">
							<p:column style="width:80%">
								#{user.fullName} - (#{user.username})
							</p:column>
						</p:autoComplete>
						<p:message for="user" />

						<p:commandButton value="Send"
							actionListener="#{proxyBean.sendProxy}" ajax="true"
							icon="ui-icon-disk" update="formPanel" />
						<p:commandButton value="Cancel" 
							action="/pages/user/home?faces-redirect=true" ajax="false" />
					</h:panelGrid>
				</p:panel>
			</h:form>
		</p:panel>
	</ui:define>

</ui:composition>

src/main/webapp/pages/user/home.xhtml
<ui:composition template="/template/layout/userLayout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="content">
		<p:panel id="introPanel" header="Signature processing">
			<p:growl id="growl" autoUpdate="true" />
			<ul>
				<li>Add and delete protected or unprotected proxies. Proxies
					usage is limited by the warrant, that specify valid period.</li>
				<li>Then you can sent newly created proxy to your company
					colleagues.</li>
				<li>Uploaded file could be signed using existing proxy or
					personal private key using DSA algorithm</li>
				<li>Signature could be verified against uploaded document</li>
			</ul>
		</p:panel>

		<p:panel header="Upload document">
			<h:form id="fileForm">
				<p:fileUpload id="upload"
					fileUploadListener="#{signBean.fileUpload.handleFileUpload}"
					update="fileForm" mode="advanced" dragDropSupport="true"
					sizeLimit="2000" auto="true">
					<p:messages id="fileMsg" showDetail="true" />
				</p:fileUpload>
			</h:form>
		</p:panel>

		<p:panel header="Upload document signature">
			<h:form id="signForm">
				<p:fileUpload id="upload" update="signForm"
					fileUploadListener="#{signBean.fileUpload.handleSignatureUpload}"
					mode="advanced" dragDropSupport="true" sizeLimit="2000" auto="true">
					<p:messages id="signMsg" showDetail="false" />
				</p:fileUpload>
			</h:form>

			<h:form id="verifyForm">
				<p:panel>
					<p:commandButton id="signBtn" value="Verify signature"
						action="#{signBean.verifySignature}" ajax="true"
						update="verifyForm" />
				</p:panel>
				
				<p:panel header="Validation results" footer="#{signBean.result.warrant == null ? 'DSA' : signBean.result.warrant.label}"
					rendered="#{signBean.result != null}">
					<ul>
						<p:panel rendered="#{signBean.result.valid}">
							<li><h:outputText value="Signature is valid" /></li>
						</p:panel>
						<p:panel rendered="#{!signBean.result.valid}">
							<li><h:outputText value="Signature is not valid" /></li>
						</p:panel>
						<p:panel rendered="#{signBean.result.proxyType == null}">
							<li><h:outputText
									value="Signed by #{signBean.result.originalSigner.fullName}" /></li>
						</p:panel>
						<p:panel rendered="#{signBean.result.proxyType != null}">
							<li><h:outputText
									value="Signed on behalf of #{signBean.result.originalSigner.fullName}" /></li>
						</p:panel>
						<p:panel rendered="#{signBean.result.proxyType == 'PROTECTED'}">
							<li><h:outputText
									value="Signed by  #{signBean.result.proxySigner.fullName}" /></li>
						</p:panel>
					</ul>
				</p:panel>
			</h:form>
		</p:panel>
	</ui:define>

</ui:composition>

src/main/webapp/pages/user/sign.xhtml
<ui:composition template="/template/layout/userLayout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://java.sun.com/jsf/core">

	<ui:define name="content">
		<p:growl id="messages" autoUpdate="true" showDetail="false" />
		<p:panel>
			<h:form id="proxyForm">
				<p:panel id="formPanel" header="Sign document">
					<h:panelGrid columns="3">
						<h:outputText id="fileName"
							value="File uploaded: "/>
						<h:outputText value="#{signBean.fileUpload.fileName}"
							rendered="#{signBean.fileUpload.fileUploaded}" />
						<h:outputText value="no uploaded file to sign" styleClass="redText"
							rendered="#{!signBean.fileUpload.fileUploaded}" />
						<p:message for="fileName" />

						<h:outputLabel for="proxyType" value="Proxy Type: " rendered="#{signBean.proxyType != null}"/>
						<p:inputText id="proxyType" value="#{signBean.proxyType.label}"
							disabled="true" rendered="#{signBean.proxyType != null}"/>
						<p:message for="proxyType" rendered="#{signBean.proxyType != null}"/>

						<p:outputLabel for="proxy" value="Choose Proxy: " rendered="#{signBean.proxyType != null}"/>
						<p:selectOneMenu id="proxy" value="#{signBean.proxy}" rendered="#{signBean.proxyType != null}"
							effect="fade" converter="#{signBean.proxyConverter}" >
							<f:selectItems value="#{signBean.proxyList}" var="proxy"
								itemLabel="#{signBean.getOriginalUserLabel(proxy)}"
								itemValue="#{proxy}" />
						</p:selectOneMenu>
						<p:message for="proxy" rendered="#{signBean.proxyType != null}"/>

						<p:commandButton value="Sign" disabled="#{signBean.fileUpload.fileUploaded == false}"
							actionListener="#{signBean.signDocUsingProxy}" ajax="true" update="formPanel"/>

						<p:commandButton value="Cancel"
							action="/pages/user/home?faces-redirect=true" ajax="false" />
					</h:panelGrid>

					<p:commandButton id="downloadLink" value="Download Signature"
						ajax="false" icon="ui-icon-disk" disabled="#{signBean.file == null}">
						<p:fileDownload value="#{signBean.file}" />
					</p:commandButton>

				</p:panel>
			</h:form>
		</p:panel>
	</ui:define>
</ui:composition>